# -*- coding: utf-8 -*-
"""выч.мат

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrxNKykikotZdG_zjO7MoNQj8e_ME3Wp
"""

import sympy as sp

# 1. Символьная часть
x = sp.symbols('x')
f_sym = x**2  # замените на вашу функцию
a = 1
b = 2

integral_analytical = sp.integrate(f_sym, (x, a, b))
print("Аналитический интеграл:", integral_analytical)

# 2. Численный метод хорды (трапеции)
def chord_method(f, a, b, n=100):
    h = (b - a) / n
    result = f(a) + f(b)
    for i in range(1, n):
        result += 2 * f(a + i*h)
    return result * h / 2

f_num = lambda x: x**2  # та же функция
integral_numerical = chord_method(f_num, a, b)
print("Интеграл методом хорды:", integral_numerical)

import sympy as sp

# 1. Символьная часть
x = sp.symbols('x')
f_sym = x**2  # замените на вашу функцию
a = 2
b = 3

integral_analytical = sp.integrate(f_sym, (x, a, b))
print("Аналитический интеграл:", integral_analytical)

# 2. Численный метод хорды (трапеции)
def chord_method(f, a, b, n=100):
    h = (b - a) / n
    result = f(a) + f(b)
    for i in range(1, n):
        result += 2 * f(a + i*h)
    return result * h / 2

f_num = lambda x: x**2  # та же функция
integral_numerical = chord_method(f_num, a, b)
print("Интеграл методом хорды:", integral_numerical)

import sympy as sp

# 1. Символьная часть
x = sp.symbols('x')
f_sym = x**2  # замените на вашу функцию
a = 3
b = 4

integral_analytical = sp.integrate(f_sym, (x, a, b))
print("Аналитический интеграл:", integral_analytical)

# 2. Численный метод хорды (трапеции)
def chord_method(f, a, b, n=100):
    h = (b - a) / n
    result = f(a) + f(b)
    for i in range(1, n):
        result += 2 * f(a + i*h)
    return result * h / 2

f_num = lambda x: x**2  # та же функция
integral_numerical = chord_method(f_num, a, b)
print("Интеграл методом хорды:", integral_numerical)

